window.gcexports.globalLexicon = {
    "val" : { "tk": 1, "name": "VAL", "cls": "function", "length": 2 , "arity": 2 },
    "key" : { "tk": 1, "name": "KEY", "cls": "function", "length": 2 , "arity": 2 },
    "len" : { "tk": 1, "name": "LEN", "cls": "function", "length": 1 , "arity": 1 },
    "concat" : { "tk": 1, "name": "CONCAT", "cls": "function", "length": 1 , "arity": 1 },
    "add" : { "tk": 1, "name": "ADD", "cls": "function", "length": 2 , "arity": 2 },
    "mul" : { "tk": 1, "name": "MUL", "cls": "function", "length": 2 , "arity": 2 },
    "style" : { "tk": 1, "name": "STYLE", "cls": "function", "length": 2, "arity": 2 },
    "map" : { "tk": 1, "name": "MAP", "cls": "function", "length": 2, "arity": 2 },
    "width" : { "tk": 1, "name": "WIDTH", "cls": "function", "length": 2, "arity": 2 },
    "height" : { "tk": 1, "name": "HEIGHT", "cls": "function", "length": 2, "arity": 2 },
    "bounds" : { "tk": 1, "name": "BOUNDS", "cls": "function", "length": 2, "arity": 2 },
    "showGrid" : { "tk": 1, "name": "SHOW-GRID", "cls": "function", "length": 1, "arity": 1 },
    "showXAxis" : { "tk": 1, "name": "SHOW-X-AXIS", "cls": "function", "length": 1, "arity": 1 },
    "showYAxis" : { "tk": 1, "name": "SHOW-Y-AXIS", "cls": "function", "length": 1, "arity": 1 },
    "in" : { "tk": 1, "name": "IN", "cls": "function", "length": 0, "arity": 0 },
    "color" : { "tk": 1, "name": "COLOR", "cls": "function", "length": 2, "arity": 2 },
    "arg" : { "tk": 1, "name": "ARG", "cls": "function", "length": 1, "arity": 1 },
    "WHITE" : { "tk": 1, "cls": "string", "val": "#ffffff", "length": 0 },
    "RED" : { "tk": 1, "cls": "string", "val": "#c74440", "length": 0 },
    "BLUE" : { "tk": 1, "cls": "string", "val": "#2d70b3", "length": 0 },
    "GREEN" : { "tk": 1, "cls": "string", "val": "#388c46", "length": 0 },
    "PURPLE" : { "tk": 1, "cls": "string", "val": "#6042a6", "length": 0 },
    "ORANGE" : { "tk": 1, "cls": "string", "val": "#fa7e19", "length": 0 },
    "BLACK" : { "tk": 1, "cls": "string", "val": "#000000", "length": 0 },
    "GREY" : { "tk": 1, "cls": "string", "val": "#aaaaaa", "length": 0 },
    "SOLID" : { "tk": 1, "cls": "string", "val": "SOLID", "length": 0 },
    "DASHED" : { "tk": 1, "cls": "string", "val": "DASHED", "length": 0 },
    "DOTTED" : { "tk": 1, "cls": "string", "val": "DOTTED", "length": 0 },
    "POINT" : { "tk": 1, "cls": "string", "val": "POINT", "length": 0 },
    "OPEN" : { "tk": 1, "cls": "string", "val": "OPEN", "length": 0 },
    "CROSS" : { "tk": 1, "cls": "string", "val": "CROSS", "length": 0 }
}
